### ISSUE TITLE
Purge operation

### ISSUE THREAD

**Issue by totchi-lagawi** [sigoden/upt#13]
UPT is really awesome (Now I will not have to deal with the one-character syntax of pacman anymore :D).
However, to uninstall a package, you can :

1. Remove the package
2. Purge the package

But UPT does not support the second method.
Could you add support for it (maybe not supported by all the package manager)?

Anyway, thanks for the project!

**Comment by sigoden** [comment]
Many package management tools do not have a so-called purge command.

Some tools provide commands like autoclean/autoremove to clean the package cache.
Some tools have remove/uninstall command which is similar to `apt purge`.

**Comment by totchi-lagawi** [comment]
Well, maybe you could add the entry for purge to the array command equivalence, and for the package managers which do not support that, you could make the application saying that it's an unsupported operation here.

However, I'm not sure whether it's hard to implement or whether it's really useful..
