### ISSUE TITLE
Add pip/pipx

### ISSUE THREAD

**Issue by Cenness** [sigoden/upt#30]
Add python package managers.
Despite their name pip and pipx are not limited to python and allow to distribute bare binaries via wheels.
https://news.ycombinator.com/item?id=31776873

Examples in the wild:
https://github.com/PyO3/maturin#usage
https://github.com/samwillis/nodejs-pypi#install

**Comment by sigoden** [comment]
Upt only supports os-level package management tools.
Upt will not support program-language-level package management tools like npm, gem, pip(x)...
