### ISSUE TITLE
Add Support for `cargo-update` and Maybe `flutter upgrade`?

### ISSUE THREAD

**Issue by ThisNekoGuy** [sigoden/upt#47]
Would be neat to add support for [cargo-update](https://github.com/nabijaczleweli/cargo-update) too.

And perhaps an option to run [`flutter upgrade`](https://docs.flutter.dev/release/upgrade)?
(Would help with not forgetting to update it but I get it's more developer-centric than cargo-update, since some apps can/are actually distributed via cargo)

**Comment by sigoden** [comment]
upt supports only OS-level package management tools in the foreseeable future.
