### ISSUE TITLE
Allow enabling multiple package systems

### ISSUE THREAD

**Issue by rcfa** [sigoden/upt#60]
Unfortunately the Linux space gets more fragmented. While the base system might use e.g. deb or rpm packages, an increasing number of software is available only as snap of flatpak.

As a result, one may have multiple package systems active concurrently, in a hierarchy of preferences.

It would be great if upt could integrate them, particularly for updates and upgrades.

The way I'd imagine: the default/top priority package system is used wherever possible (upt install), if a package there isn't found but is available in another activated system (e.g. snap or flatpak) the user is notified and given the option to install it/one of them.

upt update/upgrade does its job on all active package systems, not just the main one. That way, one command updates everything.

**Comment by sigoden** [comment]
We will not support this feature, upt is just aliases, nothing more.

**Comment by kdeldycke** [comment]
> As a result, one may have multiple package systems active concurrently, in a hierarchy of preferences.

If you want that, I maintain a project that does exactly that at: https://github.com/kdeldycke/meta-package-manager
