### ISSUE TITLE
please support these packagemanagers as well

### ISSUE THREAD

**Issue by deknos** [sigoden/upt#7]
- https://pypi.org/project/pip/
- https://rubygems.org/?locale=de
- https://docs.brew.sh/Homebrew-on-Linux
- https://brew.sh/index_de
- https://github.com/NixOS/nixpkgs
- https://github.com/devops-works/binenv

**Comment by deknos** [comment]
also please support:

- flatpak
- snap

**Comment by rokejulianlockhart** [comment]
@cacilhas, with an extension system (like what https://github.com/PackageKit/PackageKit has) https://github.com/sigoden/upt could manage both kids of packages – system or language-specific. Is that what is has now, or is that worth a feature request itself?

**Comment by sigoden** [comment]
Upt only supports thepackage management tools for OS.
Upt  does not support specific programming language package management tools such as `npm`, `gem`, `pip`, etc.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/sigoden/upt/issues/7#issuecomment-1848093835

@sigoden, that's why we're requesting this. If it wasn't restricted to those, there would be no need for the report.
